name: Mirror GitLab 🪀

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    name: Mirroring 🦾
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: GitLab Push 🚀
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ github.repository }}.git
          git push -u origin main -f
